//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Jax.Website.Models
{
	// Mixin content Type 1062 with alias "base"
	/// <summary>_base</summary>
	public partial interface IBase : IPublishedContent
	{
		/// <summary>Hero Image</summary>
		Umbraco.Web.Models.ImageCropDataSet HeroImage { get; }

		/// <summary>SEO Meta Data</summary>
		Epiphany.SeoMetadata.SeoMetadata SEometaData { get; }
	}

	/// <summary>_base</summary>
	[PublishedContentModel("base")]
	public partial class Base : PublishedContentModel, IBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "base";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Base(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Base, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Hero Image
		///</summary>
		[ImplementPropertyType("heroImage")]
		public Umbraco.Web.Models.ImageCropDataSet HeroImage
		{
			get { return GetHeroImage(this); }
		}

		/// <summary>Static getter for Hero Image</summary>
		public static Umbraco.Web.Models.ImageCropDataSet GetHeroImage(IBase that) { return that.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("heroImage"); }

		///<summary>
		/// SEO Meta Data
		///</summary>
		[ImplementPropertyType("sEOMetaData")]
		public Epiphany.SeoMetadata.SeoMetadata SEometaData
		{
			get { return GetSEometaData(this); }
		}

		/// <summary>Static getter for SEO Meta Data</summary>
		public static Epiphany.SeoMetadata.SeoMetadata GetSEometaData(IBase that) { return that.GetPropertyValue<Epiphany.SeoMetadata.SeoMetadata>("sEOMetaData"); }
	}
}
